server:
  port: 8086
  servlet:
    context-path: /
    session:
      cookie:
        same-site: none
        secure: true

spring:
  datasource:

    url: jdbc:mysql://72.61.114.184:3306/centralized?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: centralized
    password: 8kw5SGZEPCEaFejx


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: trungdev234@gmail.com
    password: ehfd fjkm jbom aktq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  servlet:
    multipart:
      max-file-size: 100MB      # đủ cho video 100MB
      max-request-size: 100MB   # tổng dung lượng cả request
      file-size-threshold: 0    # (optional) ghi thẳng ra disk, tránh ăn nhiều RAM

google:
  client-id: "42781484149-pel6vfv7rb7ih298ru93t6vq1fg8q3sq.apps.googleusercontent.com"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.mail: DEBUG

jwt:
  signerKey: "1TjXchw5FLOEsb63KcDFhTARvPWL4jUGCWfGWxgSS1f/1y/LgJxHnMqaF6A/ijXY"

payos:
  client-id: "9623941a-cb3b-4bf2-be83-b6d1d4e92b41"
  api-key: "3aa5b33a-0164-4185-b90c-8532b017e88d"
  secret-key: "b0dba29a46c36c7f1e3021da6939150f793322ed7f6323bfe98d1042a79cf8cc"
  verify-signature: true
  return-url: "https://centralized.henrytech.cloud/api/payments/success"
  cancel-url: "https://centralized.henrytech.cloud/api/payments/cancel"
  endpoint: https://api-merchant.payos.vn/v2
app:
  frontend-url: "https://centralized-language-tutor.vercel.app"

cloudflare:
  turnstile:
    secret-key: "0x4AAAAAACDzwoCLoOcK9Hu3ebIpWwM-jYw"
    enabled: true

# Cloudinary (thay API_KEY / SECRET thật của anh)
CLOUDINARY_URL: "cloudinary://972737994276791:I28XhqOy9Mi2C4v0bblGvIuthqE@dxp2w2rrx"